### ISSUE TITLE
Java adapter always logs to Kafka using Level.DEBUG

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/java-test-bed-adapter#1]
See function createLog in the CISLogger class.

A function should be added the maps the slf4j log level used to the Test-bed Log Avro schema log level.

**Comment by thoobr** [comment]
Yes I know, the function and the configuration will be available in the next version.

**Comment by PHameete** [comment]
@tobritzh yeah no rush. I'm just going through the code and making issues of whatever thing I see that still needs changing :-) Creating issues here to make sure these findings are not lost. Feel free to discuss here I prefer that over mail.

I also noted that the log messages are not formatted correctly yet because I never changed the CISLogger after an initial version.
