### ISSUE TITLE
Extrapolation of Timing

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/java-test-bed-adapter#2]
Currently the Java adapter stores a timing message received from the time server (typically one every few seconds). This timing message is then always returned when the tool requests the time from the adapter.

This should however use some form of interpolation based on the time the message was received, the time the message was sent, the simulation time speed, and the current time

**Comment by thoobr** [comment]
Yes I know, this is just for getting the timing info, the rest will be done in the next release.

**Comment by PHameete** [comment]
Perfect! I also discussed with @erikvullings we should write these functions to perform the extrapolation and share them among the different adapters to make sure that this happens consistently in every adapter.

**Comment by thoobr** [comment]
Timing is implemented  based on the implementation of TS Adapter.
