### ISSUE TITLE
Adding multiple callbacks for a single topic

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/java-test-bed-adapter#4]
I think it should be possible to add multiple callbacks to a single topic.

Currently the callbacks are mapped to a topic in a map datastructure, so adding a second callback will effectively override the first one.

This can be changed easily by adding any additional callbacks to a collection of callbacks that is mapped to a topic. The receiver can then forward the key and message to each callback that is added, rather than just one.

**Comment by thoobr** [comment]
Will be available in  the next release.

**Comment by PHameete** [comment]
Hi Thomas, is this in yet as far as you know? Or need I use a different branch?
