### ISSUE TITLE
Add functionality to remove callbacks from CISAdapter

### ISSUE THREAD

**Issue by EricNeid** [DRIVER-EU/java-test-bed-adapter#9]
Currently there is no function to remove a callback from the CISAdapter. 

The CISAdapter itself is implemented using the singleton pattern. Therefore it is difficult to reset the adapter to his original state. However this is problematic for my automatic tests. 

I suggest to add a _removeCallback(IAdapterCallback)_ function to the CISAdapter.

Is there a reason that encourages the using of the singleton pattern for the CISAdapter?

**Comment by PHameete** [comment]
Hey @thoobr I run into this issue as well when writing integration tests for the java adapter.

There is no way to 'reset' the CISAdapter, and because it is a singleton pattern the state is maintained between consecutive tests with no way to start with a clean adapter.

**Comment by thoobr** [comment]
The new version 1.2.0 implements the method: getNewInstance which destroys the old and creates a new CISAdatper instance.

**Comment by EricNeid** [comment]
That's greate news. Is the new version already available via your maven repository? Currently I'm still using version 1.0.14

**Comment by thoobr** [comment]
getNewInstance is implemented and available in release 1.2.0
